### ISSUE TITLE
Implementation Guide - Capability Statement conformance profile example missing

### ISSUE THREAD

**Issue by tylrbvn** [nhsconnect/FHIR-NOO-API#10]
The link to an example Conformance profile on the page https://nhsconnect.github.io/FHIR-NOO-API/foundations_use_case_get_the_fhir_conformance_profile.html is dead

This can be found at the bottom of the page in the Request Response  > Payload Response Body section and directs to here https://nhsconnect.github.io/FHIR-NOO-API/Conformance/NDOP-CapabilityStatement-1.xml

**Comment by dxh73** [comment]
Will update the link with a working version once I have a capabilityStatement to link too. Thanks for spotting this.

**Comment by dxh73** [comment]
Link to an example capabilityStatement fixed.
