### ISSUE TITLE
Implementation Guide - sourceofoptout extension page error handling refers to birthDate

### ISSUE THREAD

**Issue by tylrbvn** [nhsconnect/FHIR-NOO-API#9]
The following page in the implementation guide refers to birthDate in the error handling section https://nhsconnect.github.io/FHIR-NOO-API/consent_extension_sourceofoptout.html

Presumably this has been taken from elsewhere and not replaced?

**Comment by dxh73** [comment]
Yes, its left over from a page that was used as a template. I'll get it fixed. Thanks for spotting this.

**Comment by dxh73** [comment]
Birth date removed from page.
